### ISSUE TITLE
Version 0.0.3

### ISSUE THREAD

**Issue by canassa** [kennethreitz/stathat.py#6]
Hi,

The version currently available on PyPI is very old and does not contain the latest commits. It would be very nice if could bump the version and release it on PyPI.

Thanks!

**Comment by brunotikami** [comment]
:+1:

**Comment by wiliamsouza** [comment]
:+1:

**Comment by muminoff** [comment]
:+1:

**Comment by kennethreitz** [comment]
released! (finally)

**Comment by kennethreitz** [comment]
https://pypi.python.org/pypi/stathat
